[sedes_internas]
; =========================================
; EXTENSIONES LOCALES (PREFIJO 1)
; =========================================

; Extensiones Locales de su Sede (Sede 1)
exten => _10X,1,Dial(PJSIP/${EXTEN},30,tT)
exten => _10X,n,Hangup()

; =========================================
; SERVICIOS PBX EMPRESARIALES
; =========================================

; 1. Sala de Conferencia (Marcando 812)
exten => 812,1,Answer()
exten => 812,n,Playback(conf-getpin)
exten => 812,n,ConfBridge(sala_novalink)
exten => 812,n,Hangup()

; 2. Código de Prueba de Audio (Marcando 811) - Echo Test
exten => 811,1,Answer()
exten => 811,n,Echo()
exten => 811,n,Hangup()

; =========================================
; SALIDA A RED PÚBLICA (PSTN)
; =========================================
; Simulación de salida PSTN (Prefijo 9 + 7 o más dígitos)
exten => _9XXXXXXX!,1,NoOp(--- Llamada Saliente PSTN ---)
exten => _9XXXXXXX!,n,Answer()
exten => _9XXXXXXX!,n,Playback(vm-goodbye)
exten => _9XXXXXXX!,n,Hangup()

; =========================================
; ENRUTAMIENTO EXTERNO (HACIA SEDE 2)
; =========================================
; Enrutamiento hacia Sede 2 (Sergio)
exten => _2XX,1,NoOp(--- Enrutando llamada hacia Sede 2 ---)
exten => _2XX,n,Dial(PJSIP/${EXTEN}@trunk-sede2,30,tT)
exten => _2XX,n,Hangup()
