; ====================================================================
; NovaLink C.A. - Sistema de Logs y Depuración de Asterisk
; ====================================================================

[general]
dateformat=%F %T
rotatestrategy=rotate

[logfiles]
; Salida hacia la consola de Asterisk (CLI)
console => notice,warning,error

; Archivo por defecto: /var/log/asterisk/messages
messages => notice,warning,error,security
