; =========================================
; TRANSPORTE
; =========================================

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/asterisk.crt
priv_key_file=/etc/asterisk/keys/asterisk.key
method=tlsv1_2
verify_client=no
verify_server=no

; =========================================
; PLANTILLA BASE PARA EXTENSIONES
; =========================================
[endpoint-basic](!)
type=endpoint
context=sedes_internas
disallow=all
allow=ulaw
allow=alaw
transport=transport-tls
media_encryption=sdes
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
rtp_timeout=60
rtp_timeout_hold=900

; =========================================
; EXTENSIÓN 101
; =========================================
[101](endpoint-basic)
auth=auth101
aors=101

[auth101]
type=auth
auth_type=userpass
password=secreto101
username=101

[101]
type=aor
max_contacts=1
remove_existing=yes

; =========================================
; EXTENSIÓN 102
; =========================================
[102](endpoint-basic)
auth=auth102
aors=102

[auth102]
type=auth
auth_type=userpass
password=secreto102
username=102

[102]
type=aor
max_contacts=1
remove_existing=yes

; =========================================
; TRONCAL HACIA SEDE 2
; =========================================
[trunk-sede2]
type=endpoint
transport=transport-tls
context=sedes_internas ; Permite que las llamadas de tu compañero entren a tus extensiones
disallow=all
allow=g722
allow=ulaw
allow=alaw
media_encryption=sdes
aors=trunk-sede2
rtp_timeout=60
rtp_timeout_hold=900

[trunk-sede2]
type=aor
contact=sip:10.59.225.244:5061

[trunk-sede2]
type=identify
endpoint=trunk-sede2
match=10.59.225.244
