; =========================================
; TRANSPORTE
; =========================================
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; =========================================
; PLANTILLA BASE PARA EXTENSIONES
; =========================================
[endpoint-basic](!)
type=endpoint
context=sedes_internas
disallow=all
allow=ulaw
allow=alaw

; =========================================
; EXTENSIÓN 1001
; =========================================
[1001](endpoint-basic)
auth=auth1001
aors=1001

[auth1001]
type=auth
auth_type=userpass
password=secreto1001
username=1001

[1001]
type=aor
max_contacts=1

; =========================================
; EXTENSIÓN 1002
; =========================================
[1002](endpoint-basic)
auth=auth1002
aors=1002

[auth1002]
type=auth
auth_type=userpass
password=secreto1002
username=1002

[1002]
type=aor
max_contacts=1

; =========================================
; TRONCAL HACIA SEDE 2
; =========================================
[trunk-sede2]
type=endpoint
transport=transport-udp
context=sedes_internas ; Permite que las llamadas de tu compañero entren a tus extensiones
disallow=all
allow=ulaw
allow=alaw
aors=trunk-sede2

[trunk-sede2]
type=aor
contact=sip:[IP_DE_TU_COMPAÑERO]:5060

[trunk-sede2]
type=identify
endpoint=trunk-sede2
match=10.59.225.244
