; ====================================================================
; NovaLink C.A. - Configuración de Puertos y Temporizadores RTP
; ====================================================================

[general]
; Rango de puertos UDP para medios RTP
rtpstart=10000
rtpend=20000

; Desconexión si no hay paquetes RTP durante 60 segundos
rtptimeout=60

; Límite estricto de 900 segundos (15 minutos) para llamadas en retención (Hold) sin tráfico RTP
rtpholdtimeout=900

; Verificación de sumas de comprobación RTP
rtpchecksums=yes
