; ====================================================================
; NovaLink C.A. - Salas de Conferencias (ConfBridge)
; ====================================================================

[general]

; Perfil de usuario por defecto
[default_user]
type=user
music_on_hold_when_empty=yes
music_on_hold_class=default
announce_user_count=yes
announce_join_leave=yes
talk_detection_events=yes

; Perfil del puente de conferencia por defecto
[default_bridge]
type=bridge
max_members=50
record_conference=no
internal_sample_rate=auto
mixing_interval=20

; Menú DTMF para participantes
[default_menu]
type=menu
*1 = toggle_mute
*4 = decrease_listening_volume
*6 = increase_listening_volume
