[sedes_internas]
; =========================================
; EXTENSIONES LOCALES
; =========================================

; Extensión 2001 (Tú)
exten => 2001,1,Dial(PJSIP/2001,30,tT)
exten => 2001,n,Hangup()

; Extensión 2002
exten => 2002,1,Dial(PJSIP/2002,30,tT)
exten => 2002,n,Hangup()

; =========================================
; SERVICIOS PBX EMPRESARIALES
; =========================================

; 1. Código de Prueba de Audio (Marcando 2111)
exten => 2111,1,Answer()
exten => 2111,n,Echo()
exten => 2111,n,Hangup()

; 2. Sala de Conferencias Empresarial (Marcando 2112)
exten => 2112,1,NoOp(--- Ingreso a Sala de Conferencias 2112 ---)
exten => 2112,n,Answer()
exten => 2112,n,ConfBridge(2112,default_bridge,default_user,default_menu)
exten => 2112,n,Hangup()

; =========================================
; ENRUTAMIENTO EXTERNO
; =========================================
; Cualquier número que empiece con 1 y tenga 4 dígitos, se envía por ZeroTier
exten => _1XXX,1,Dial(PJSIP/${EXTEN}@trunk-sede1,30,tT)
exten => _1XXX,n,Hangup()
