[sedes_internas]
; =========================================
; EXTENSIONES LOCALES (SEDE 2)
; =========================================
exten => _20X,1,Dial(PJSIP/${EXTEN},30,tT)
exten => _20X,n,Hangup()

; =========================================
; SERVICIOS PBX EMPRESARIALES
; =========================================
exten => 811,1,Answer()
exten => 811,n,Echo()
exten => 811,n,Hangup()

exten => 812,1,NoOp(--- Ingreso a Sala de Conferencias 812 ---)
exten => 812,n,Answer()
exten => 812,n,ConfBridge(812,default_bridge,default_user,default_menu)
exten => 812,n,Hangup()

; =========================================
; ENRUTAMIENTO HACIA OTRAS SEDES
; =========================================
; Cualquier extensión de 3 dígitos que empiece por 1 se manda a la Sede 1
exten => _1XX,1,NoOp(--- Enrutando llamada hacia Sede 1 ---)
exten => _1XX,n,Dial(PJSIP/${EXTEN}@trunk-sede1,30,tT)
exten => _1XX,n,Hangup()

; =========================================
; ENRUTAMIENTO RED PÚBLICA / SALIENTE (Prefijo 9)
; =========================================
; Cualquier número que empiece por 9 y tenga al menos 7 dígitos más.
exten => _9XXXXXXX.,1,NoOp(--- Llamada Saliente a la Red Pública Simulada ---)
exten => _9XXXXXXX.,n,Answer()
exten => _9XXXXXXX.,n,Playback(pbx-invalid) ; Reproduce un mensaje temporal
exten => _9XXXXXXX.,n,Hangup()
