; =========================================
; TRANSPORTES
; =========================================
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; Transporte Seguro TLS
[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/asterisk.crt
priv_key_file=/etc/asterisk/keys/asterisk.key
method=sslv23
verify_client=no
verify_server=no

; =========================================
; PLANTILLA BASE PARA EXTENSIONES
; =========================================
[endpoint-basic](!)
type=endpoint
context=sedes_internas
disallow=all
allow=g722
allow=ulaw
allow=alaw
; Obligamos a usar la vía segura y cifrado SRTP
transport=transport-tls
media_encryption=sdes

; =========================================
; EXTENSIÓN 2001
; =========================================
[2001](endpoint-basic)
auth=auth2001
aors=2001

[auth2001]
type=auth
auth_type=userpass
password=secreto2001
username=2001

[2001]
type=aor
max_contacts=1

; =========================================
; EXTENSIÓN 2002
; =========================================
[2002](endpoint-basic)
auth=auth2002
aors=2002

[auth2002]
type=auth
auth_type=userpass
password=secreto2002
username=2002

[2002]
type=aor
max_contacts=1

; =========================================
; TRONCAL HACIA SEDE 1
; =========================================
[trunk-sede1]
type=endpoint
context=sedes_internas
disallow=all
allow=g722
allow=ulaw
allow=alaw
; La troncal también se blinda
transport=transport-tls
media_encryption=sdes
aors=trunk-sede1

[trunk-sede1]
type=aor
; Cambiamos el puerto de destino al 5061
contact=sip:10.59.225.105:5061

[trunk-sede1]
type=identify
endpoint=trunk-sede1
match=10.59.225.105
