; =========================================
; TRANSPORTES
; =========================================
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; Transporte Seguro TLS
[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/asterisk.crt
priv_key_file=/etc/asterisk/keys/asterisk.key
method=sslv23
verify_client=no
verify_server=no

; =========================================
; PLANTILLA BASE PARA EXTENSIONES
; =========================================
[endpoint-basic](!)
type=endpoint
context=sedes_internas
disallow=all
allow=g722
allow=ulaw
allow=alaw
; Obligamos a usar la vía segura y cifrado SRTP
transport=transport-tls
media_encryption=sdes

; Temporizadores RTP (flujo de audio)
rtp_timeout=60
rtp_timeout_hold=900

; SIP Session Timers
timers=yes
timers_min_se=90
timers_sess_expires=900

; =========================================
; EXTENSIÓN 201
; =========================================
[201](endpoint-basic)
auth=auth201
aors=201

[auth201]
type=auth
auth_type=userpass
password=secreto201
username=201

[201]
type=aor
max_contacts=1
remove_existing=yes

; =========================================
; EXTENSIÓN 202
; =========================================
[202](endpoint-basic)
auth=auth202
aors=202

[auth202]
type=auth
auth_type=userpass
password=secreto202
username=202

[202]
type=aor
max_contacts=1
remove_existing=yes

; =========================================
; TRONCAL HACIA SEDE 1
; =========================================
[trunk-sede1]
type=endpoint
context=sedes_internas
disallow=all
allow=g722
allow=ulaw
allow=alaw
transport=transport-tls
media_encryption=sdes

; Temporizadores RTP
rtp_timeout=60
rtp_timeout_hold=900

; SIP Session Timers
timers=yes
timers_min_se=90
timers_sess_expires=900

aors=trunk-sede1

[trunk-sede1]
type=aor
; Cambiamos el puerto de destino al 5061
contact=sip:10.59.225.35:5061

[trunk-sede1]
type=identify
endpoint=trunk-sede1
match=10.59.225.35
